"""initial

Revision ID: 094a03f05704
Revises: 
Create Date: 2025-12-13 12:46:45.925106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094a03f05704'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_email'), 'tbl_user', ['email'], unique=True)
    op.create_index(op.f('ix_tbl_user_id'), 'tbl_user', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_uid'), 'tbl_user', ['uid'], unique=True)
    op.create_table('sync_logs_we_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_we_budget_id'), 'sync_logs_we_budget', ['id'], unique=False)
    op.create_table('tbl_analytic_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analytic_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_expense', sa.Float(), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=False),
    sa.Column('top_category', sa.String(), nullable=True),
    sa.Column('top_merchant', sa.String(), nullable=True),
    sa.Column('overspent_categories', sa.String(), nullable=True),
    sa.Column('favorite_spending_time', sa.String(), nullable=True),
    sa.Column('favorite_merchant', sa.String(), nullable=True),
    sa.Column('prediction_next_month_expense', sa.Float(), nullable=True),
    sa.Column('saving_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_analytic_cache_analytic_id'), 'tbl_analytic_cache', ['analytic_id'], unique=True)
    op.create_index(op.f('ix_tbl_analytic_cache_id'), 'tbl_analytic_cache', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_analytic_cache_month'), 'tbl_analytic_cache', ['month'], unique=False)
    op.create_index(op.f('ix_tbl_analytic_cache_user_id'), 'tbl_analytic_cache', ['user_id'], unique=False)
    op.create_index(op.f('ix_tbl_analytic_cache_year'), 'tbl_analytic_cache', ['year'], unique=False)
    op.create_table('tbl_bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('starting_balance', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_bank_account_account_id'), 'tbl_bank_account', ['account_id'], unique=True)
    op.create_index(op.f('ix_tbl_bank_account_account_number'), 'tbl_bank_account', ['account_number'], unique=False)
    op.create_index(op.f('ix_tbl_bank_account_bank_name'), 'tbl_bank_account', ['bank_name'], unique=False)
    op.create_index(op.f('ix_tbl_bank_account_currency'), 'tbl_bank_account', ['currency'], unique=False)
    op.create_index(op.f('ix_tbl_bank_account_id'), 'tbl_bank_account', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_bank_account_starting_balance'), 'tbl_bank_account', ['starting_balance'], unique=False)
    op.create_index(op.f('ix_tbl_bank_account_user_id'), 'tbl_bank_account', ['user_id'], unique=False)
    op.create_table('tbl_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_category_category_id'), 'tbl_category', ['category_id'], unique=True)
    op.create_index(op.f('ix_tbl_category_category_name'), 'tbl_category', ['category_name'], unique=False)
    op.create_index(op.f('ix_tbl_category_description'), 'tbl_category', ['description'], unique=False)
    op.create_index(op.f('ix_tbl_category_id'), 'tbl_category', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_category_type'), 'tbl_category', ['type'], unique=False)
    op.create_index(op.f('ix_tbl_category_user_id'), 'tbl_category', ['user_id'], unique=False)
    op.create_table('tbl_family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('family_name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_family_family_id'), 'tbl_family', ['family_id'], unique=True)
    op.create_index(op.f('ix_tbl_family_id'), 'tbl_family', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_family_user_id'), 'tbl_family', ['user_id'], unique=False)
    op.create_table('tbl_partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_partner_code'), 'tbl_partner', ['code'], unique=False)
    op.create_index(op.f('ix_tbl_partner_email'), 'tbl_partner', ['email'], unique=False)
    op.create_index(op.f('ix_tbl_partner_id'), 'tbl_partner', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_partner_name'), 'tbl_partner', ['name'], unique=True)
    op.create_index(op.f('ix_tbl_partner_partner_id'), 'tbl_partner', ['partner_id'], unique=True)
    op.create_index(op.f('ix_tbl_partner_user_id'), 'tbl_partner', ['user_id'], unique=False)
    op.create_table('tbl_user_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('blocked_status', sa.String(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_device_blocked_status'), 'tbl_user_device', ['blocked_status'], unique=False)
    op.create_index(op.f('ix_tbl_user_device_device_id'), 'tbl_user_device', ['device_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_device_id'), 'tbl_user_device', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_device_reason'), 'tbl_user_device', ['reason'], unique=False)
    op.create_index(op.f('ix_tbl_user_device_user_id'), 'tbl_user_device', ['user_id'], unique=False)
    op.create_table('tbl_family_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('member_name', sa.String(), nullable=False),
    sa.Column('birthdate', sa.String(), nullable=True),
    sa.Column('family_relationship', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['tbl_family.family_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_family_member_birthdate'), 'tbl_family_member', ['birthdate'], unique=False)
    op.create_index(op.f('ix_tbl_family_member_code'), 'tbl_family_member', ['code'], unique=False)
    op.create_index(op.f('ix_tbl_family_member_family_id'), 'tbl_family_member', ['family_id'], unique=False)
    op.create_index(op.f('ix_tbl_family_member_family_relationship'), 'tbl_family_member', ['family_relationship'], unique=False)
    op.create_index(op.f('ix_tbl_family_member_id'), 'tbl_family_member', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_family_member_member_name'), 'tbl_family_member', ['member_name'], unique=False)
    op.create_table('tbl_recurring_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurring_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_recurring_transaction_category_id'), 'tbl_recurring_transaction', ['category_id'], unique=False)
    op.create_index(op.f('ix_tbl_recurring_transaction_id'), 'tbl_recurring_transaction', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_recurring_transaction_recurring_id'), 'tbl_recurring_transaction', ['recurring_id'], unique=True)
    op.create_index(op.f('ix_tbl_recurring_transaction_user_id'), 'tbl_recurring_transaction', ['user_id'], unique=False)
    op.create_table('tbl_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_transaction_amount'), 'tbl_transaction', ['amount'], unique=False)
    op.create_index(op.f('ix_tbl_transaction_category_id'), 'tbl_transaction', ['category_id'], unique=False)
    op.create_index(op.f('ix_tbl_transaction_id'), 'tbl_transaction', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_transaction_merchant_name'), 'tbl_transaction', ['merchant_name'], unique=False)
    op.create_index(op.f('ix_tbl_transaction_notes'), 'tbl_transaction', ['notes'], unique=False)
    op.create_index(op.f('ix_tbl_transaction_transaction_date'), 'tbl_transaction', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_tbl_transaction_transaction_id'), 'tbl_transaction', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_tbl_transaction_transaction_type'), 'tbl_transaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_tbl_transaction_user_id'), 'tbl_transaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_transaction_user_id'), table_name='tbl_transaction')
    op.drop_index(op.f('ix_tbl_transaction_transaction_type'), table_name='tbl_transaction')
    op.drop_index(op.f('ix_tbl_transaction_transaction_id'), table_name='tbl_transaction')
    op.drop_index(op.f('ix_tbl_transaction_transaction_date'), table_name='tbl_transaction')
    op.drop_index(op.f('ix_tbl_transaction_notes'), table_name='tbl_transaction')
    op.drop_index(op.f('ix_tbl_transaction_merchant_name'), table_name='tbl_transaction')
    op.drop_index(op.f('ix_tbl_transaction_id'), table_name='tbl_transaction')
    op.drop_index(op.f('ix_tbl_transaction_category_id'), table_name='tbl_transaction')
    op.drop_index(op.f('ix_tbl_transaction_amount'), table_name='tbl_transaction')
    op.drop_table('tbl_transaction')
    op.drop_index(op.f('ix_tbl_recurring_transaction_user_id'), table_name='tbl_recurring_transaction')
    op.drop_index(op.f('ix_tbl_recurring_transaction_recurring_id'), table_name='tbl_recurring_transaction')
    op.drop_index(op.f('ix_tbl_recurring_transaction_id'), table_name='tbl_recurring_transaction')
    op.drop_index(op.f('ix_tbl_recurring_transaction_category_id'), table_name='tbl_recurring_transaction')
    op.drop_table('tbl_recurring_transaction')
    op.drop_index(op.f('ix_tbl_family_member_member_name'), table_name='tbl_family_member')
    op.drop_index(op.f('ix_tbl_family_member_id'), table_name='tbl_family_member')
    op.drop_index(op.f('ix_tbl_family_member_family_relationship'), table_name='tbl_family_member')
    op.drop_index(op.f('ix_tbl_family_member_family_id'), table_name='tbl_family_member')
    op.drop_index(op.f('ix_tbl_family_member_code'), table_name='tbl_family_member')
    op.drop_index(op.f('ix_tbl_family_member_birthdate'), table_name='tbl_family_member')
    op.drop_table('tbl_family_member')
    op.drop_index(op.f('ix_tbl_user_device_user_id'), table_name='tbl_user_device')
    op.drop_index(op.f('ix_tbl_user_device_reason'), table_name='tbl_user_device')
    op.drop_index(op.f('ix_tbl_user_device_id'), table_name='tbl_user_device')
    op.drop_index(op.f('ix_tbl_user_device_device_id'), table_name='tbl_user_device')
    op.drop_index(op.f('ix_tbl_user_device_blocked_status'), table_name='tbl_user_device')
    op.drop_table('tbl_user_device')
    op.drop_index(op.f('ix_tbl_partner_user_id'), table_name='tbl_partner')
    op.drop_index(op.f('ix_tbl_partner_partner_id'), table_name='tbl_partner')
    op.drop_index(op.f('ix_tbl_partner_name'), table_name='tbl_partner')
    op.drop_index(op.f('ix_tbl_partner_id'), table_name='tbl_partner')
    op.drop_index(op.f('ix_tbl_partner_email'), table_name='tbl_partner')
    op.drop_index(op.f('ix_tbl_partner_code'), table_name='tbl_partner')
    op.drop_table('tbl_partner')
    op.drop_index(op.f('ix_tbl_family_user_id'), table_name='tbl_family')
    op.drop_index(op.f('ix_tbl_family_id'), table_name='tbl_family')
    op.drop_index(op.f('ix_tbl_family_family_id'), table_name='tbl_family')
    op.drop_table('tbl_family')
    op.drop_index(op.f('ix_tbl_category_user_id'), table_name='tbl_category')
    op.drop_index(op.f('ix_tbl_category_type'), table_name='tbl_category')
    op.drop_index(op.f('ix_tbl_category_id'), table_name='tbl_category')
    op.drop_index(op.f('ix_tbl_category_description'), table_name='tbl_category')
    op.drop_index(op.f('ix_tbl_category_category_name'), table_name='tbl_category')
    op.drop_index(op.f('ix_tbl_category_category_id'), table_name='tbl_category')
    op.drop_table('tbl_category')
    op.drop_index(op.f('ix_tbl_bank_account_user_id'), table_name='tbl_bank_account')
    op.drop_index(op.f('ix_tbl_bank_account_starting_balance'), table_name='tbl_bank_account')
    op.drop_index(op.f('ix_tbl_bank_account_id'), table_name='tbl_bank_account')
    op.drop_index(op.f('ix_tbl_bank_account_currency'), table_name='tbl_bank_account')
    op.drop_index(op.f('ix_tbl_bank_account_bank_name'), table_name='tbl_bank_account')
    op.drop_index(op.f('ix_tbl_bank_account_account_number'), table_name='tbl_bank_account')
    op.drop_index(op.f('ix_tbl_bank_account_account_id'), table_name='tbl_bank_account')
    op.drop_table('tbl_bank_account')
    op.drop_index(op.f('ix_tbl_analytic_cache_year'), table_name='tbl_analytic_cache')
    op.drop_index(op.f('ix_tbl_analytic_cache_user_id'), table_name='tbl_analytic_cache')
    op.drop_index(op.f('ix_tbl_analytic_cache_month'), table_name='tbl_analytic_cache')
    op.drop_index(op.f('ix_tbl_analytic_cache_id'), table_name='tbl_analytic_cache')
    op.drop_index(op.f('ix_tbl_analytic_cache_analytic_id'), table_name='tbl_analytic_cache')
    op.drop_table('tbl_analytic_cache')
    op.drop_index(op.f('ix_sync_logs_we_budget_id'), table_name='sync_logs_we_budget')
    op.drop_table('sync_logs_we_budget')
    op.drop_index(op.f('ix_tbl_user_uid'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_id'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_email'), table_name='tbl_user')
    op.drop_table('tbl_user')
    # ### end Alembic commands ###
