"""add new column is_verified

Revision ID: 1f27e24e3cd6
Revises: 568afad530f9
Create Date: 2025-12-19 15:56:39.710020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f27e24e3cd6'
down_revision: Union[str, None] = '568afad530f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sync_logs_we_budget', 'tbl_user', ['user_id'], ['uid'])
    op.create_foreign_key(None, 'tbl_analytic_cache', 'tbl_user', ['user_id'], ['uid'])
    op.create_foreign_key(None, 'tbl_bank_account', 'tbl_user', ['user_id'], ['uid'])
    op.create_foreign_key(None, 'tbl_category', 'tbl_user', ['user_id'], ['uid'])
    op.create_foreign_key(None, 'tbl_family', 'tbl_user', ['user_id'], ['uid'])
    op.create_foreign_key(None, 'tbl_partner', 'tbl_user', ['user_id'], ['uid'])
    op.create_foreign_key(None, 'tbl_recurring_transaction', 'tbl_user', ['user_id'], ['uid'])
    op.create_foreign_key(None, 'tbl_transaction', 'tbl_user', ['user_id'], ['uid'])
    op.add_column('tbl_user', sa.Column('is_verified', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.create_foreign_key(None, 'tbl_user_device', 'tbl_user', ['user_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_user_device', type_='foreignkey')
    op.drop_column('tbl_user', 'is_verified')
    op.drop_constraint(None, 'tbl_transaction', type_='foreignkey')
    op.drop_constraint(None, 'tbl_recurring_transaction', type_='foreignkey')
    op.drop_constraint(None, 'tbl_partner', type_='foreignkey')
    op.drop_constraint(None, 'tbl_family', type_='foreignkey')
    op.drop_constraint(None, 'tbl_category', type_='foreignkey')
    op.drop_constraint(None, 'tbl_bank_account', type_='foreignkey')
    op.drop_constraint(None, 'tbl_analytic_cache', type_='foreignkey')
    op.drop_constraint(None, 'sync_logs_we_budget', type_='foreignkey')
    # ### end Alembic commands ###
