"""change column name names to name

Revision ID: 568afad530f9
Revises: 094a03f05704
Create Date: 2025-12-19 13:24:45.233288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568afad530f9'
down_revision: Union[str, None] = '094a03f05704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('tbl_user', 'name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False,
    #            new_column_name='name')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               new_column_name='names')
    # ### end Alembic commands ###
