apiVersion: apps/v1
kind: Deployment
metadata:
  name: primovative-app-deployment
  labels:
    app: primovative-app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primovative-app-api
  template:
    metadata:
      labels:
        app: primovative-app-api
    spec:
      containers:
        - name: nodeserver
          image: primovative/primovative-app-api:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: primovative-app-service
spec:
  selector:
    app: primovative-app-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31110
