"""add column to user is_verified

Revision ID: 155edc7cca66
Revises: 776d108fa519
Create Date: 2025-06-15 16:24:10.179052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155edc7cca66'
down_revision: Union[str, None] = '776d108fa519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('is_verified', sa.Boolean(), nullable=True, default=False))
    op.execute("UPDATE tbl_users SET is_verified = false")
    op.alter_column('tbl_users', 'is_verified', nullable=False)  
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_users', 'is_verified')
    # ### end Alembic commands ###
