"""add email to users

Revision ID: 776d108fa519
Revises: de808125f3f7
Create Date: 2025-06-15 15:28:45.988516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776d108fa519'
down_revision: Union[str, None] = 'de808125f3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tbl_users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_users', type_='unique')
    op.drop_column('tbl_users', 'email')
    # ### end Alembic commands ###
