"""ImageColumn-changed

Revision ID: a76dc130afe5
Revises: 54ff167505ed
Create Date: 2025-02-10 20:57:52.653929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76dc130afe5'
down_revision: Union[str, None] = '54ff167505ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('tbl_images')
    # op.drop_table('tbl_users')
    op.alter_column("tbl_images", "image_page", new_column_name="image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        # op.create_table('tbl_users',
        # sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tbl_users_id_seq'::regclass)"), autoincrement=True, nullable=False),
        # sa.Column('userId', sa.VARCHAR(), autoincrement=False, nullable=True),
        # sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
        # sa.PrimaryKeyConstraint('id', name='tbl_users_pkey'),
        # sa.UniqueConstraint('userId', name='tbl_users_userId_key'),
        # postgresql_ignore_search_path=False
        # )
        # op.create_table('tbl_images',
        # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        # sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True),
        # sa.Column('image_page', sa.VARCHAR(), autoincrement=False, nullable=True),
        # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        # sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name='tbl_images_user_id_fkey'),
        # sa.PrimaryKeyConstraint('id', name='tbl_images_pkey')
        # )
        op.alter_column("tbl_images", "image_url", new_column_name="image_page")
    # ### end Alembic commands ###
